// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-mn-Jhg8VNVM3o8f4CPpOXeD6A94FDo4',
    appId: '1:36387606232:web:63ba363f5a2fe2203211ad',
    messagingSenderId: '36387606232',
    projectId: 'practicasapupeu',
    authDomain: 'practicasapupeu.firebaseapp.com',
    storageBucket: 'practicasapupeu.firebasestorage.app',
    measurementId: 'G-J4VPSJEM1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZWj35DMSTyjGzam8Fl3jrMRgclzojBGk',
    appId: '1:36387606232:android:847a3ebb870140883211ad',
    messagingSenderId: '36387606232',
    projectId: 'practicasapupeu',
    storageBucket: 'practicasapupeu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8weY4WJVEO_UruaqLNTZBlY_Hm9Kvjmo',
    appId: '1:36387606232:ios:bf4c46c714fd8aec3211ad',
    messagingSenderId: '36387606232',
    projectId: 'practicasapupeu',
    storageBucket: 'practicasapupeu.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.practicasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8weY4WJVEO_UruaqLNTZBlY_Hm9Kvjmo',
    appId: '1:36387606232:ios:bf4c46c714fd8aec3211ad',
    messagingSenderId: '36387606232',
    projectId: 'practicasapupeu',
    storageBucket: 'practicasapupeu.firebasestorage.app',
    iosBundleId: 'pe.edu.upeu.practicasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-mn-Jhg8VNVM3o8f4CPpOXeD6A94FDo4',
    appId: '1:36387606232:web:bf0087702c6147ec3211ad',
    messagingSenderId: '36387606232',
    projectId: 'practicasapupeu',
    authDomain: 'practicasapupeu.firebaseapp.com',
    storageBucket: 'practicasapupeu.firebasestorage.app',
    measurementId: 'G-RR3ZPN92R1',
  );
}
